
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lireddit2
    username: postgres
    password: Weisses2
    dialect: PostgresqlDialect
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

graphql:
  packages: "com.lireddit.example"